version: '3'
services:
  mysqldb:
    image: mysql:latest
    environment:
      - MYSQL_USER=root
      - MYSQL_DATABASE=devops
    ports:
      - "3306:3306"     
    volumes:
      - db:/var/lib/mysql
  backend:
    depends_on:
      - mysqldb
    build: ./
    restart: on-failure
    ports:
      - "8089:8089"
    stdin_open: true
    tty: true
    volumes:
      - .m2:/root/.m2    
volumes:
  db:
