version: '3.8'
services:
  # MySQL Database
  mysqldb:
    image: mysql:latest 
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: devops
      MYSQL_USER: root
      MYSQL_PASSWORD:
    volumes:
      - db:/var/lib/mysql
  # Backend SpringBoot
  gestion-station-ski-backend:
    depends_on:
      - mysql:latest
    image: stationski-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8089:8089
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/devops?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
volumes:
  db :
